### PR TITLE
Adjust allowed attributes for the `many`

### PR DESCRIPTION
**Pull request by makenosound**
Removes the various `allowed_` attributes and adds some simple display attributes.

### CODE REVIEW

**Comment by timriley** [comment]
This looks fine to me. I just wish I could think of a better name for `add_label` :weary: 

Elsewhere in formalist, we have a lot of plain `label` attributes, and `selector_label`. `add_label` feels funny to me here because it could be mistaken as a verb.

`creation_label`? `item_addition_label`? `action_label`? `add_action_label`? `add_button_label`? (though I know we've tried to make the attributes not too UI-implementation-specific in the past)

**Comment by makenosound** [comment]
`action_label` seems reasonable to me. I’ll adjust.

**Comment by timriley** [comment]
Cool. Happy for you to merge!

**Comment by makenosound** [comment]
I’m doin’ it, I’m doin’ it.

**Pull request merged**
